---
#-----------------------[Config by DerCooleVonDem]-----------------------
#
#-----------------------[ğ““ğ“ğ“˜ğ“£ ğ“«ğ”‚ ğ““ğ“®ğ“»ğ“’ğ“¸ğ“¸ğ“µğ“®ğ“¥ğ“¸ğ“·ğ““ğ“®ğ“¶ 2021]-----------------
#
#
#
#
# {command} = The Command Name which was executed.
# The Message will appear when the Command user doesn't have the Permission to use it.
#no-permission-message: "Â§cSorry, but you dont have the Permission to use {command}!"
#
# {command} = The Command which was executed for Everyone.
# When someone executed [/everyone <command>] then this message will appear for him.
#everyone-message: "Â§a{command} was successfully executed for EVERYONE"
#
# {command} = The Command which was executed for {victim}.
# {victim} = The user for whom the command was executed.
# When someone executed [/run <victim> <command>] then this message will appear for him.
#run-message: "Â§a{command} was successfully executed for {victim}"
#
# {command} = The Command which was executed for the Console.
# When someone executed [/console <command>] then this message will appear for him.
#console-message: "Â§a{command} was successfully executed for the Console"
#
# {command} = The Command which was executed for the Console.
# When someone executed [/others <command>] then this message will appear for him.
#others-message: "Â§a{command} was successfully executed for everyone but you"
#
# Any Problems with the Plugin?
# Send me a friend request above Discord and write me!
# Discord: DerCooleVonDem#9991
#
#
...